name: 'dbt_artifacts'
version: '2.1.1'
config-version: 2
require-dbt-version: ">=1.2.0"
profile: "dbt_artifacts"

clean-targets: # folders to be removed by `dbt clean`
  - "target"
  - "dbt_packages"
  - "logs"

models:
  dbt_artifacts:
    +materialized: view
    +file_format: delta
    sources:
      +materialized: incremental
      +on_schema_change: append_new_columns
      +full_refresh: false
